version: 1.0.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: src/Conditions.sln

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: Conditions\bin\Release\Conditions.dll
    name: Conditions.dll
  - path: '**\*.nupkg'
